### ISSUE TITLE
Gifffer distorts long images

### ISSUE THREAD

**Issue by maryfries** [krasimir/gifffer#10]
I'm finding that the gifffer is distorting images that are significantly longer than they are wide. 

![gifffer-distortion2](https://cloud.githubusercontent.com/assets/6549787/15193636/e3d3bdea-178c-11e6-8969-e09493158ed4.gif)

Any idea why or how to fix?

**Comment by krasimir** [comment]
That's interesting. Can you please provide an URL with the example. Or at least post the markup.

**Comment by maryfries** [comment]
It could be something in our legacy code. I'd be interested to know if you figure it out: http://bjc-edc.github.io/bjc-r/cur/programming/2-conditionals-abstraction-testing/1-conditionals/2-creating-predicates.html?topic=nyc_bjc%2F2-conditionals-abstraction.topic&course=bjc4nyc_2015-2016.html&novideo&noassignment This is a working draft of http://bjc.edc.org Thanks! Great script!

**Comment by krasimir** [comment]
Must be something with your page. It looks like the problem is not in Gifffer or in the image. Check out this page http://trash.krasimirtsonev.com/gifffer/ We don't see the distorting if there is no other styles. So, I'll suggest to debug your page by cutting styles and see which of them causes the issue.

**Comment by maryfries** [comment]
I needed to add `img {padding:0px;}` to the CSS. Thanks!
