### ISSUE TITLE
Doesn't play from where it was paused in Safari

### ISSUE THREAD

**Issue by rahul-desai3** [krasimir/gifffer#8]
I am playing your demo on Safari v9.0.2 on Mac OSX El Capitan and the GIF starts from the beginning when I play it back again after pausing.

Is there a way to fix this?

**Comment by krasimir** [comment]
@rahul-desai3 I don't think so. That's because what we are doing is making a screenshot of the first frame and just replacing the real gif with static email. When you hit play again we just swap the static image with the animated gif. So it's not like we have all the frames from the gif. 

However, there are plenty of other issues reported and I'm thinking rewriting the library or at least make a research for some other mechanisms to accomplish the same thing.

**Comment by rahul-desai3** [comment]
Gotcha.
